// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Order struct {
	ID             int64  `json:"id"`
	UserID         int64  `json:"user_id"`
	SeckillEventID int64  `json:"seckill_event_id"`
	Amount         string `json:"amount"`
	// created, paid, cancelled
	Status    string       `json:"status"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Product struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	ImageUrl    string    `json:"image_url"`
	Price       string    `json:"price"`
	CreatedAt   time.Time `json:"created_at"`
}

type SeckillEvent struct {
	ID        int64     `json:"id"`
	ProductID int64     `json:"product_id"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
	// The total inventory for this activity
	StockCount int64 `json:"stock_count"`
	// Remaining inventory
	RemainingStock int64        `json:"remaining_stock"`
	SeckillPrice   string       `json:"seckill_price"`
	CreatedAt      sql.NullTime `json:"created_at"`
}

type User struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	// bcrypt Hash
	Password  string       `json:"password"`
	Email     string       `json:"email"`
	CreatedAt sql.NullTime `json:"created_at"`
}
