// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package db

import (
	"context"
)

const createOrder = `-- name: CreateOrder :one

INSERT INTO orders(
  user_id,seckill_event_id,amount,status
) VALUES(
  $1,$2,$3,$4
) RETURNING id, user_id, seckill_event_id, amount, status, created_at
`

type CreateOrderParams struct {
	UserID         int64  `json:"user_id"`
	SeckillEventID int64  `json:"seckill_event_id"`
	Amount         string `json:"amount"`
	Status         string `json:"status"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder,
		arg.UserID,
		arg.SeckillEventID,
		arg.Amount,
		arg.Status,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SeckillEventID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, user_id, seckill_event_id, amount, status, created_at FROM orders
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrder(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SeckillEventID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
