// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateSeckillEvent(ctx context.Context, arg CreateSeckillEventParams) (SeckillEvent, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetOrder(ctx context.Context, id int64) (Order, error)
	GetProduct(ctx context.Context, id int64) (Product, error)
	GetSeckillEvent(ctx context.Context, id int64) (SeckillEvent, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListActiveSeckillEvents(ctx context.Context) ([]ListActiveSeckillEventsRow, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ReduceInventory(ctx context.Context, id int64) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
