// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seckill.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createSeckillEvent = `-- name: CreateSeckillEvent :one
INSERT INTO seckill_events (
  product_id,start_time,end_time,stock_count,remaining_stock,seckill_price
) VALUES(
   $1, $2, $3, $4, $5, $6
) RETURNING id, product_id, start_time, end_time, stock_count, remaining_stock, seckill_price, created_at
`

type CreateSeckillEventParams struct {
	ProductID      int64     `json:"product_id"`
	StartTime      time.Time `json:"start_time"`
	EndTime        time.Time `json:"end_time"`
	StockCount     int64     `json:"stock_count"`
	RemainingStock int64     `json:"remaining_stock"`
	SeckillPrice   string    `json:"seckill_price"`
}

func (q *Queries) CreateSeckillEvent(ctx context.Context, arg CreateSeckillEventParams) (SeckillEvent, error) {
	row := q.db.QueryRowContext(ctx, createSeckillEvent,
		arg.ProductID,
		arg.StartTime,
		arg.EndTime,
		arg.StockCount,
		arg.RemainingStock,
		arg.SeckillPrice,
	)
	var i SeckillEvent
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.StartTime,
		&i.EndTime,
		&i.StockCount,
		&i.RemainingStock,
		&i.SeckillPrice,
		&i.CreatedAt,
	)
	return i, err
}

const getSeckillEvent = `-- name: GetSeckillEvent :one
SELECT id, product_id, start_time, end_time, stock_count, remaining_stock, seckill_price, created_at FROM seckill_events
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSeckillEvent(ctx context.Context, id int64) (SeckillEvent, error) {
	row := q.db.QueryRowContext(ctx, getSeckillEvent, id)
	var i SeckillEvent
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.StartTime,
		&i.EndTime,
		&i.StockCount,
		&i.RemainingStock,
		&i.SeckillPrice,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveSeckillEvents = `-- name: ListActiveSeckillEvents :many
SELECT
  se.id, se.product_id, se.start_time, se.end_time, se.stock_count, se.remaining_stock, se.seckill_price, se.created_at,
  p.name as product_name,
  p.image_url as product_image
FROM seckill_events se
JOIN products p ON se.product_id = p.id
WHERE se.start_time <= now() AND se.end_time >= now()
ORDER BY se.start_time ASC
`

type ListActiveSeckillEventsRow struct {
	ID             int64        `json:"id"`
	ProductID      int64        `json:"product_id"`
	StartTime      time.Time    `json:"start_time"`
	EndTime        time.Time    `json:"end_time"`
	StockCount     int64        `json:"stock_count"`
	RemainingStock int64        `json:"remaining_stock"`
	SeckillPrice   string       `json:"seckill_price"`
	CreatedAt      sql.NullTime `json:"created_at"`
	ProductName    string       `json:"product_name"`
	ProductImage   string       `json:"product_image"`
}

func (q *Queries) ListActiveSeckillEvents(ctx context.Context) ([]ListActiveSeckillEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSeckillEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveSeckillEventsRow
	for rows.Next() {
		var i ListActiveSeckillEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.StartTime,
			&i.EndTime,
			&i.StockCount,
			&i.RemainingStock,
			&i.SeckillPrice,
			&i.CreatedAt,
			&i.ProductName,
			&i.ProductImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reduceInventory = `-- name: ReduceInventory :execresult
UPDATE seckill_events
SET remaining_stock = remaining_stock - 1
WHERE id = $1 AND remaining_stock > 0
`

func (q *Queries) ReduceInventory(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, reduceInventory, id)
}
